In [1]:
import numpy as np 

In [5]:
import matplotlib as plt
import pandas as pd
import seaborn as se


In [ ]:
# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("nikhatabdulsalam/fifa-world-cup-2022-pts-table")

# print("Path to dataset files:", path)

Path to dataset files: /carrot/Documents/ML/ml-practise-weekwise/data


In [11]:
import pandas as pd

df = pd.read_csv("data/Fifa World Cup Points Table.csv")

In [13]:
data = [10,20,30,40]
labels = ['a', 'b', 'c', 'd']

series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [2]:
a =np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D
b= np.array([[1,2,3],[4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [4]:
#3D
c = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [5]:
np.array([1,2,3] ,dtype=float)

array([1., 2., 3.])

In [6]:
np.array([1,2,3] ,dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
np.arange(
    1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,99,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [10]:
np.arange(1,21).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.random.random((3,4))

array([[0.1053251 , 0.22715682, 0.92468031, 0.7893943 ],
       [0.53440655, 0.20226601, 0.29017561, 0.11531475],
       [0.24594563, 0.44286029, 0.33598588, 0.85522008]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
a1 = np.arange(10)
a2= np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [22]:
a2.ndim

2

In [23]:
a1.shape

(10,)

In [26]:
a2.shape
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [28]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
print(a3.size)

8


In [33]:
a2.itemsize

8

In [34]:
print(a1.dtype)

int64


In [38]:
# changing datatype

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [41]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)

print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [42]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [44]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [47]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [48]:
a2>20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [49]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [50]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [52]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[62., 94., 45.],
       [78., 63., 64.],
       [ 4., 73., 29.]])

In [54]:
np.max(a1)

np.float64(94.0)

In [55]:
np.sum(a1)

np.float64(512.0)

In [57]:
np.prod(a1)

np.float64(698438277089280.0)

In [60]:
# 0 -> col and 1 -> row

np.max(a1,axis = 1)

array([94., 78., 73.])

In [61]:
np.prod(a1,axis = 1)

array([262260., 314496.,   8468.])

In [62]:
np.mean(a1)

np.float64(56.888888888888886)

In [63]:
np.mean(a1,axis=0)

array([48.        , 76.66666667, 46.        ])

In [65]:
np.var(a1, axis = 0) #variance

array([1010.66666667,  166.88888889,  204.66666667])

In [66]:
np.sin(a1)

array([[-0.7391807 , -0.24525199,  0.85090352],
       [ 0.51397846,  0.1673557 ,  0.92002604],
       [-0.7568025 , -0.67677196, -0.66363388]])

In [68]:

a1 = np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(4,3)

np.dot (a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [69]:
np.log(a1)

/tmp/ipykernel_34674/2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [73]:
np.round(np.random.random((2,3))*100)


array([[93., 98., 30.],
       [65., 93.,  9.]])

In [74]:
np.floor(np.random.random((2,3))*100)

array([[81., 71., 43.],
       [84.,  0., 92.]])

In [78]:
a2 = np.arange(12).reshape(3,4)

In [79]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
a2[1,2]

np.int64(6)

In [84]:
a2[2,3]

np.int64(11)

In [91]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [92]:
a2[1,::3]

array([4, 7])

In [95]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [96]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [98]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [100]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [101]:
a3[0,1]

array([3, 4, 5])

In [104]:
a3[2,:,1]

array([19, 22, 25])

In [109]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [110]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [111]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [112]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [113]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [114]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [119]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [120]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [121]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [123]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]