In [1]:
import numpy as np

In [2]:
b = np.arange(4,10)
b

array([4, 5, 6, 7, 8, 9])

In [7]:
a= np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
a[1,2]

np.int64(5)

In [5]:
###fancy indexing


a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [9]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [19]:
a=np.random.randint(1,100,24).reshape(6,4)
a


array([[79, 36, 86, 35],
       [31, 77, 36, 31],
       [40, 44, 71, 85],
       [75, 50, 83, 38],
       [52, 88, 50, 43],
       [61, 91,  1, 94]])

In [20]:
a >50

array([[ True, False,  True, False],
       [False,  True, False, False],
       [False, False,  True,  True],
       [ True, False,  True, False],
       [ True,  True, False, False],
       [ True,  True, False,  True]])

In [21]:
a[a>50]

array([79, 86, 77, 71, 85, 75, 83, 52, 88, 61, 91, 94])

In [22]:
a%2==0

array([[False,  True,  True, False],
       [False, False,  True, False],
       [ True,  True, False, False],
       [False,  True, False,  True],
       [ True,  True,  True, False],
       [False, False, False,  True]])

In [23]:
a[a%2==0]

array([36, 86, 36, 40, 44, 50, 38, 52, 88, 50, 94])

In [29]:
a[(a>50 ) & (a%2==0)]

array([86, 52, 88, 94])

In [30]:
a[a%7==0]

array([35, 77, 91])

In [31]:
a[~(a%7==0)]

array([79, 36, 86, 31, 36, 31, 40, 44, 71, 85, 75, 50, 83, 38, 52, 88, 50,
       43, 61,  1, 94])

In [32]:
######
#Broadcasting

In [34]:
a= np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a+b)



[[0 2 4]
 [3 5 7]]


In [40]:
a= np.arange(12).reshape(4,3)
b = np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [42]:
a= np.arange(12).reshape(3,4)
b = np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [43]:
a= np.arange(10)
np.sum(a)

np.int64(45)

In [44]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [47]:
#sigmoid

def sigmoid(array):
    return 1/(1+np.exp(-(array)))

a = np.arange(100)

sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [ ]:
#mean squared error
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [52]:
def mse(actual,predicted):
    return np.mean ((actual-predicted)**2)
print(mse(actual,predicted))

461.4


In [54]:
##missing vaeus

a= np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [57]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])