In [1]:

import numpy as np

In [6]:
a= np.random.randint(1,100,15)
a

array([56,  6, 63, 19, 21, 23, 43, 49, 43, 61, 47, 39, 26, 88, 76])

In [21]:
b= np.random.randint(1,100,24).reshape(6,4)

b

array([[55, 55, 69, 58],
       [89, 49, 68, 83],
       [54, 26, 21, 48],
       [74, 71, 39, 76],
       [54, 75, 62, 20],
       [43, 22, 72, 16]])

In [4]:
np.sort(a)

array([ 5,  7,  8, 10, 12, 14, 38, 48, 49, 52, 61, 64, 66, 91, 98])

In [6]:
np.sort(b,axis=0)

array([[22, 52, 17, 15],
       [25, 52, 18, 19],
       [36, 66, 26, 30],
       [36, 68, 35, 37],
       [74, 77, 88, 50],
       [97, 93, 97, 56]])

In [7]:
np.sort(b,axis=1)

array([[35, 37, 68, 97],
       [30, 52, 74, 88],
       [19, 22, 93, 97],
       [26, 36, 50, 52],
       [17, 36, 56, 66],
       [15, 18, 25, 77]])

In [ ]:
#descending order 2nd way
np.sort(a)[::1]

array([ 5,  7,  8, 10, 12, 14, 38, 48, 49, 52, 61, 64, 66, 91, 98])

In [9]:
a

array([ 8, 49, 48, 61,  7, 98, 91, 66, 38, 64, 52, 14, 10,  5, 12])

In [10]:
np.append(a,200)

array([  8,  49,  48,  61,   7,  98,  91,  66,  38,  64,  52,  14,  10,
         5,  12, 200])

In [13]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[9.70000000e+01, 6.80000000e+01, 3.50000000e+01, 3.70000000e+01,
        3.98787197e-02],
       [7.40000000e+01, 5.20000000e+01, 8.80000000e+01, 3.00000000e+01,
        1.18321505e-01],
       [2.20000000e+01, 9.30000000e+01, 9.70000000e+01, 1.90000000e+01,
        6.15407495e-01],
       [3.60000000e+01, 5.20000000e+01, 2.60000000e+01, 5.00000000e+01,
        7.47635580e-04],
       [3.60000000e+01, 6.60000000e+01, 1.70000000e+01, 5.60000000e+01,
        1.43344289e-01],
       [2.50000000e+01, 7.70000000e+01, 1.80000000e+01, 1.50000000e+01,
        9.85340131e-01]])

In [2]:
c = np.arange(6).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
d = np.arange(6,12).reshape(2,3)
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [5]:
e = np.array([1,2,3,4,4,5,1,2,1,1,2,4,5,6,6,7,7])
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
a.shape

(15,)

In [7]:
np.expand_dims(a,axis=0)

array([[56,  6, 63, 19, 21, 23, 43, 49, 43, 61, 47, 39, 26, 88, 76]])

In [9]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [10]:
np.expand_dims(a,axis=1)

array([[56],
       [ 6],
       [63],
       [19],
       [21],
       [23],
       [43],
       [49],
       [43],
       [61],
       [47],
       [39],
       [26],
       [88],
       [76]])

In [11]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [12]:
a


array([56,  6, 63, 19, 21, 23, 43, 49, 43, 61, 47, 39, 26, 88, 76])

In [13]:
np.where(a>50)

(array([ 0,  2,  9, 13, 14]),)

In [14]:
# np.where(condition,true,false)

np.where(a>50,0,a)

array([ 0,  6,  0, 19, 21, 23, 43, 49, 43,  0, 47, 39, 26,  0,  0])

In [15]:
np.where(a%2==0,0,a)

array([ 0,  0, 63, 19, 21, 23, 43, 49, 43, 61, 47, 39,  0,  0,  0])

In [16]:
a

array([56,  6, 63, 19, 21, 23, 43, 49, 43, 61, 47, 39, 26, 88, 76])

In [19]:
c=np.argmax(a)
print(c)

13


In [22]:
b

array([[55, 55, 69, 58],
       [89, 49, 68, 83],
       [54, 26, 21, 48],
       [74, 71, 39, 76],
       [54, 75, 62, 20],
       [43, 22, 72, 16]])

In [23]:
np.argmax(b,axis=0)

array([1, 4, 5, 1])

In [24]:
np.argmax(b,axis=1)

array([2, 0, 0, 3, 1, 2])

In [26]:
np.argmin(a)

np.int64(1)

In [27]:
a

array([56,  6, 63, 19, 21, 23, 43, 49, 43, 61, 47, 39, 26, 88, 76])

In [ ]:
# cumulative sum
np.cumsum(a)

array([ 56,  62, 125, 144, 165, 188, 231, 280, 323, 384, 431, 470, 496,
       584, 660])

In [29]:
b

array([[55, 55, 69, 58],
       [89, 49, 68, 83],
       [54, 26, 21, 48],
       [74, 71, 39, 76],
       [54, 75, 62, 20],
       [43, 22, 72, 16]])

In [30]:
np.cumsum(b)

array([  55,  110,  179,  237,  326,  375,  443,  526,  580,  606,  627,
        675,  749,  820,  859,  935,  989, 1064, 1126, 1146, 1189, 1211,
       1283, 1299])

In [31]:
np.cumsum(b,axis=0)

array([[ 55,  55,  69,  58],
       [144, 104, 137, 141],
       [198, 130, 158, 189],
       [272, 201, 197, 265],
       [326, 276, 259, 285],
       [369, 298, 331, 301]])

In [33]:
np.cumsum(b,axis=1)

array([[ 55, 110, 179, 237],
       [ 89, 138, 206, 289],
       [ 54,  80, 101, 149],
       [ 74, 145, 184, 260],
       [ 54, 129, 191, 211],
       [ 43,  65, 137, 153]])

In [34]:
a

array([56,  6, 63, 19, 21, 23, 43, 49, 43, 61, 47, 39, 26, 88, 76])

In [35]:
np.cumprod(a)

array([                  56,                  336,                21168,
                     402192,              8446032,            194258736,
                 8353125648,         409303156752,       17600035740336,
           1073602180160496,    50459302467543312,  1967912796234189168,
       -4174499519039736480,  1578923798694222080, -9128999815205983232])

In [36]:
a

array([56,  6, 63, 19, 21, 23, 43, 49, 43, 61, 47, 39, 26, 88, 76])

In [38]:
np.percentile(a,100)

np.float64(88.0)

In [39]:
np.percentile(a,0)

np.float64(6.0)

In [40]:
np.percentile(a,50)

np.float64(43.0)

In [41]:
np.median(a)

np.float64(43.0)

In [42]:
np.percentile(a,75)

np.float64(58.5)

In [43]:
a

array([56,  6, 63, 19, 21, 23, 43, 49, 43, 61, 47, 39, 26, 88, 76])

In [45]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 3, 1, 4, 1, 2, 1, 1, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [48]:
# correlation coefficients
salary = np.array([20000,40000,50000,700000])
experience= np.array([1,2,3,4])

np.corrcoef(salary,experience)

array([[1.        , 0.79738775],
       [0.79738775, 1.        ]])

In [49]:
a

array([56,  6, 63, 19, 21, 23, 43, 49, 43, 61, 47, 39, 26, 88, 76])

In [50]:
items = [10,203,30,40,506,56,43]
np.isin(a,items)

array([ True, False, False, False, False, False,  True, False,  True,
       False, False, False, False, False, False])

In [51]:
a

array([56,  6, 63, 19, 21, 23, 43, 49, 43, 61, 47, 39, 26, 88, 76])

In [52]:
np.flip(a)

array([76, 88, 26, 39, 47, 61, 43, 49, 43, 23, 21, 19, 63,  6, 56])

In [53]:
b

array([[55, 55, 69, 58],
       [89, 49, 68, 83],
       [54, 26, 21, 48],
       [74, 71, 39, 76],
       [54, 75, 62, 20],
       [43, 22, 72, 16]])

In [54]:
np.flip(b)

array([[16, 72, 22, 43],
       [20, 62, 75, 54],
       [76, 39, 71, 74],
       [48, 21, 26, 54],
       [83, 68, 49, 89],
       [58, 69, 55, 55]])

In [55]:
np.flip(b,axis =0)

array([[43, 22, 72, 16],
       [54, 75, 62, 20],
       [74, 71, 39, 76],
       [54, 26, 21, 48],
       [89, 49, 68, 83],
       [55, 55, 69, 58]])

In [59]:
a

array([110, 530,  63,  19,  21,  23,  43,  49,  43,  61,  47,  39,  26,
        88,  76])

In [58]:
np.put(a,[0,1],[110,530])

In [60]:
np.delete(a,0)

array([530,  63,  19,  21,  23,  43,  49,  43,  61,  47,  39,  26,  88,
        76])

In [61]:
np.delete(a,[0,4,5])

array([530,  63,  19,  43,  49,  43,  61,  47,  39,  26,  88,  76])

In [62]:
m= np.array([1,2,3,4,5])
n= np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [63]:
np.intersect1d(m,n)

array([3, 4, 5])

In [64]:
np.setdiff1d(m,n)

array([1, 2])

In [65]:
np.setdiff1d(n,m)

array([6, 7])

In [66]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [71]:
a

array([110, 530,  63,  19,  21,  23,  43,  49,  43,  61,  47,  39,  26,
        88,  76])

In [73]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 63, 25, 25, 25, 43, 49, 43, 61, 47, 39, 26, 75, 75])